bugfix test publish

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -55,9 +55,13 @@ jobs:
       - name: Install TinyTeX
         run: |
           quarto install tinytex
-          export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH # Explicitly add TinyTeX to PATH
-          sudo chmod -R a+rx $HOME/.TinyTeX                 # Fix permissions if necessary
-
+          export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH
+          sudo chmod -R a+rx $HOME/.TinyTeX # Fix permissions if necessary
+          if ! command -v tlmgr &> /dev/null; then
+            echo "TinyTeX installation failed or tlmgr is not in PATH"
+            exit 1
+          fi
+      
       - name: Verify TinyTeX Installation
         run: |
           export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH # Ensure PATH is updated
